export const pageConfig = [
  {
    name: "首页",
    pathName: "homehome",
    key: "home",
    path: "/",
    icon: "i-mdi-home",
  },
  {
    name: "系统管理",
    pathName: "systemUser",
    key: "system_user",
    path: "/system",
    icon: "i-mdi-cog",
    buttons: ["system_user_add", "system_user_edit"],
    children: [],
  },
  {
    name: "系统管理2",
    pathName: "systemUser2",
    key: "system_user",
    path: "/system2",
    icon: "i-mdi-cog",
    buttons: ["system_user_edit"],
    children: [],
  },
  {
    name: "用户管理",
    pathName: "systemUserTest",
    key: "system_user_test",
    single: true,
    newWindow: true,
    path: "/system/userWindow",
    icon: "i-mdi-user",
    buttons: ["system_user_test_edit", "system_user_test_add"],
  },
  {
    name: "用户管理no new window",
    pathName: "systemUserTest2",
    key: "system_user_test",
    single: true,
    newWindow: false,
    path: "/system/user",
    icon: "i-mdi-user",
    buttons: ["system_user_test_add"],
  },
];
